### ISSUE TITLE
Cpp parser choose different (wrong) rule compare to java.

### ISSUE THREAD

**Issue by Nic30** [DanMcLaughlin/antlr4#12] opened 2016-06-27 16:35 UTC
Using grammar https://raw.githubusercontent.com/antlr/grammars-v4/master/vhdl/vhdl.g4
(I had to change name of NULL terminal to T_NULL, https://github.com/Nic30/HWToolkit/blob/cppHdlParser/hdl_toolkit/parser/hdlConvertor/vhdl.g4)
I am getting different results with java and c++ parser generated from same grammar (using antlr4-4.5.4-SNAPSHOT.jar). 

All original examples for the grammar are affected 
https://github.com/antlr/grammars-v4/tree/master/vhdl/examples

In rule "package_body_declarative_item" - "subprogram_declaration" is always chosen instead of "subprogram_body". I do not know why this happening and I was not able to make basic example which demonstrates the bug.

Minimal input to reproduce error:
```
package body package0 is
 function fn0 (param0 : bit_vector)
                   return bit is  
  begin
    -- function code
  end fn0;
end package0;
```

`ParserATNSimulator::adaptivePredict` returns wrong value.

_serializedATNSegment0 and 1 are same in Java and Cpp parser.

_decisionToDFA seems to be same (stateNumber and nonGreedy prop.)

**Comment by nuuman** [comment] 2016-06-27 19:54
Are you parsing with the same prediction mode in C++ and Java? (SLL for instance)

**Comment by Nic30** [comment] 2016-06-27 20:10
I tried SLL, LL and LL_EXACT_AMBIG_DETECTION. All of them ends up with same error.
3:30:Error:mismatched input 'is' expecting {RANGE, TOLERANCE, BASIC_IDENTIFIER, EXTENDED_IDENTIFIER, ';', '(', '.'}
7:0:Error:extraneous input 'end' expecting {<EOF>, ARCHITECTURE, CONFIGURATION, ENTITY, LIBRARY, PACKAGE, USE}

**Comment by Nic30** [comment] 2016-06-27 20:17
Java version still works after changing NULL -> T_NULL
(https://github.com/Nic30/HWToolkit/tree/cppHdlParser/hdl_toolkit/parser   
hdlParser - c++
vhdlParser - java
)

**Comment by nuuman** [comment] 2016-06-27 20:34
No idea then, hopefully @mike-lischke can look into it.

**Comment by Nic30** [comment] 2016-06-27 20:57
Only thing I found out is that issue is not directly caused by rules where the error is happening.
It seems like some more generic error in prediction resolving, but hard to say.
I check it by Valgrind and I don't see any invalid reads etc.

**Comment by nuuman** [comment] 2016-06-28 09:18
> It seems like some more generic error in prediction resolving

Sounds nasty

**Comment by mike-lischke** [comment] 2016-06-28 09:51
I'll check this when I get time. Might take a while, though.

**Comment by Nic30** [comment] 2016-06-28 11:58
I made a simplified version https://github.com/Nic30/antlr4_vhdl_debug.
But it still is not trivial and I still did not identify the rule which causing issue.

**Comment by nuuman** [comment] 2016-06-28 13:06
Can you simplify further?

**Comment by Nic30** [comment] 2016-06-28 15:19
I am trying but there is too much rules which I just touch and error disappears. 
I have nearly no knowledge of ANTLR so I do not know what I am search for.

**Comment by mike-lischke** [comment] 2016-06-29 10:12
I cannot reproduce any problem with that. I used the original VHDL grammar (changed NULL to NULL_SYM) and generated the parsers from that:

![parser-compare](https://cloud.githubusercontent.com/assets/2398704/16448624/bb574b3e-3df2-11e6-86fb-645ea2d30b02.png)

**Comment by nuuman** [comment] 2016-06-29 10:41
@mike-lischke So the examples at  https://github.com/antlr/grammars-v4/tree/master/vhdl/examples work fine in the C++ parser as well?

**Comment by mike-lischke** [comment] 2016-06-29 11:29
Sometimes yes, sometimes no. There is a random behavior actually, which could mean there is some missing initialization for a var or so.

**Comment by nuuman** [comment] 2016-06-29 12:58
Yeah, or an unstable sort... something subtle for sure.

**Comment by Nic30** [comment] 2016-06-30 14:58
It did not worked for me so I downloaded newest version. 
(commit 6de938dbf793a779588a044d8e1783dbf9c8fc32 )
After first run it crashed on null pointer dereference deep inside antlr.
I was happy because I was thinking that now I can find what is wrong.

Downloaded original grammar and made changes same as @mike-lischke.
And it is still same. I have same code like him (https://github.com/Nic30/antlr4_vhdl_debug).

Stack:
```
Thread #1 [antlr4_vhdl_deb] 28540 [core: 9] (Suspended : Signal : SIGSEGV:Segmentation fault)	
	antlr4::atn::LexerActionExecutor::generateHashCode() at LexerActionExecutor.cpp:121 0x682290	
	antlr4::atn::LexerActionExecutor::LexerActionExecutor() at LexerActionExecutor.cpp:45 0x6819a0	
	__gnu_cxx::new_allocator<antlr4::atn::LexerActionExecutor>::construct<antlr4::atn::LexerActionExecutor, std::vector<std::shared_ptr<antlr4::atn::LexerAction>, std::allocator<std::shared_ptr<antlr4::atn::LexerAction> > > >() at new_allocator.h:120 0x684ba6	
	std::allocator_traits<std::allocator<antlr4::atn::LexerActionExecutor> >::construct<antlr4::atn::LexerActionExecutor, std::vector<std::shared_ptr<antlr4::atn::LexerAction>, std::allocator<std::shared_ptr<antlr4::atn::LexerAction> > > >() at alloc_traits.h:530 0x6848ae	
	std::_Sp_counted_ptr_inplace<antlr4::atn::LexerActionExecutor, std::allocator<antlr4::atn::LexerActionExecutor>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<std::vector<std::shared_ptr<antlr4::atn::LexerAction>, std::allocator<std::shared_ptr<antlr4::atn::LexerAction> > > > at shared_ptr_base.h:522 0x684370	
	std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<antlr4::atn::LexerActionExecutor, std::allocator<antlr4::atn::LexerActionExecutor>, std::vector<std::shared_ptr<antlr4::atn::LexerAction>, std::allocator<std::shared_ptr<antlr4::atn::LexerAction> > > > at shared_ptr_base.h:617 0x683d99	
	std::__shared_ptr<antlr4::atn::LexerActionExecutor, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<antlr4::atn::LexerActionExecutor>, std::vector<std::shared_ptr<antlr4::atn::LexerAction>, std::allocator<std::shared_ptr<antlr4::atn::LexerAction> > > > at shared_ptr_base.h:1,097 0x683a48	
	std::shared_ptr<antlr4::atn::LexerActionExecutor>::shared_ptr<std::allocator<antlr4::atn::LexerActionExecutor>, std::vector<std::shared_ptr<antlr4::atn::LexerAction>, std::allocator<std::shared_ptr<antlr4::atn::LexerAction> > > >() at shared_ptr.h:319 0x6837b2	
	std::allocate_shared<antlr4::atn::LexerActionExecutor, std::allocator<antlr4::atn::LexerActionExecutor>, std::vector<std::shared_ptr<antlr4::atn::LexerAction>, std::allocator<std::shared_ptr<antlr4::atn::LexerAction> > > >() at shared_ptr.h:620 0x68318e	
	std::make_shared<antlr4::atn::LexerActionExecutor, std::vector<std::shared_ptr<antlr4::atn::LexerAction>, std::allocator<std::shared_ptr<antlr4::atn::LexerAction> > > >() at shared_ptr.h:636 0x682bb3	
	antlr4::atn::LexerActionExecutor::append() at LexerActionExecutor.cpp:51 0x681a93	
	antlr4::atn::LexerATNSimulator::getEpsilonTarget() at LexerATNSimulator.cpp:451 0x67b605	
	antlr4::atn::LexerATNSimulator::closure() at LexerATNSimulator.cpp:382 0x67b12d	
	antlr4::atn::LexerATNSimulator::closure() at LexerATNSimulator.cpp:384 0x67b193	
	antlr4::atn::LexerATNSimulator::closure() at LexerATNSimulator.cpp:384 0x67b193	
	antlr4::atn::LexerATNSimulator::closure() at LexerATNSimulator.cpp:384 0x67b193	
	antlr4::atn::LexerATNSimulator::getReachableConfigSet() at LexerATNSimulator.cpp:285 0x67a735	
	antlr4::atn::LexerATNSimulator::computeTargetState() at LexerATNSimulator.cpp:223 0x67a140	
	antlr4::atn::LexerATNSimulator::execATN() at LexerATNSimulator.cpp:176 0x679f44	
	antlr4::atn::LexerATNSimulator::match() at LexerATNSimulator.cpp:105 0x679b58	
	antlr4::Lexer::nextToken() at Lexer.cpp:103 0x6d291c	
	antlr4::BufferedTokenStream::fetch() at BufferedTokenStream.cpp:122 0x6c7566	
	antlr4::BufferedTokenStream::fill() at BufferedTokenStream.cpp:430 0x6c947e	
	main() at main.cpp:28 0x60c6f1	

```

lexerAction is null in LexerActionExecutor::generateHashCode()

**Comment by nuuman** [comment] 2016-06-30 20:46
The lexerActions code should be more robust IMO.

LexerATNSimulator.cpp#450 for instance:

            Ref<LexerActionExecutor> lexerActionExecutor = LexerActionExecutor::append(config->getLexerActionExecutor(),
          atn.lexerActions[static_cast<ActionTransition *>(t)->actionIndex]);

where

    atn.lexerActions[

should be replaced with

    atn.lexerActions.at

so that out-of-bounds are checked. If actionIndex is out of bounds, you may, depending on compiler, get a null in the lexerActions vector, which could cause your segfault.

**Comment by Nic30** [comment] 2016-07-01 07:46
@nuuman No nothing has changed, patch is there:

https://github.com/Nic30/antlr4_vhdl_debug/blob/master/antlr-patches/use_atFn_insteadOf_indexing_on_atn_lexerActions.patch

**Comment by nuuman** [comment] 2016-07-01 08:32
@Nic30 thanks for trying

**Comment by nuuman** [comment] 2016-07-07 11:32
OK, I'm definitely hitting this myself now, with my own grammar. Very hard to figure out what's going on.

@mike-lischke I think this is a very serious problem, does this get any priority?

**Comment by Nic30** [comment] 2016-07-07 12:20
I would be nice to have some visual debug tool (like org.antlr.v4.gui.TestRig) for c++ as well.
Or is there any way how to use it with c++ runtime?

**Comment by Nic30** [comment] 2016-07-08 15:38
In PredictionModeClass::getConflictingAltSubsets
there is 6 items in configs->configs and they have different hashes (in java and cpp) but cpp configToAlts has only 5 values (java 6 as it should be). This seems to be only difference in cpp/java parser which I found and it is causing this issue.

Why hash functions does not return same type in cpp and java? It makes debugging harder.

**Comment by Nic30** [comment] 2016-07-08 17:37
why AltAndContextConfigHasher and AltAndContextConfigComparer are used instead of regular hashCode and == in PredictionModeClass::getConflictingAltSubsets
It seems that this is the root of this issue.

**Comment by mike-lischke** [comment] 2016-07-20 13:37
Hashes in Java and C++ are different because the C++ target uses 64bit hashes (and not signed), so they are not directly comparable. But if the number of config entries differs then something is definitely wrong. Maybe 2 entries are considered equal where they shouldn't be. Can you check when exactly the `configToAlts` lists start to differ? Btw. the hashes don't play a big role here (and anywhere else), they are just used to find a proper bucket in the hash map. So they only decide about the efficiency of the algorithm, not the correctness. The real work is done in the == operator overloading.

About `AltAndContextConfigHasher` and `AltAndContextConfigComparer`: these are stripped down variants for sorting in `getConflictingAltSubsets` (same as in Java), as for this special comparison only state number and context are used, while the standard comparison additionally considers other members, like alt, semantic context and suppressed precedence filters. This is by intention.

**Comment by Nic30** [comment] 2016-07-26 11:30
https://github.com/Nic30/antlr4/wiki/getConflictingAltSubsets-configs-content-difference

**Comment by Nic30** [comment] 2016-07-26 11:58
In SingletonPredictionContext::operator ==
There is
```cpp
if (this->hashCode() != other->hashCode()) {
    return false; // can't be same if hash is different
  }
```
In java hash codes are different in cpp they are same.

**Comment by mike-lischke** [comment] 2016-07-26 13:46
Now it would be good to find out why they are the same in C++, when they shouldn't. However hash codes in prediction contexts are cached. You could temporarily always compute them on demand to allow inspecting the context's properties. Also try disabling the hash code comparison temporarily.

**Comment by Nic30** [comment] 2016-07-26 14:29
Problem actually is that configs are not correct. 
(upper cpp, lower java)
 ```
((ATNState 0x2974a50) {
  state: INVALID  (1413)
  ruleIndex: 115
  epsilonOnlyTransitions: 0
  transistions (1):
    SET (Transition 0x29adea0, target: 0x2974ab0) { set: {118..119}}
},
1,
[1716 2445 [1509 1518 1520 1547 1311 2424 2408 2380 1791 $, 1602 1518 1520 1547 1311 2424 2408 2380 1791 $]])

(1413,
1,
[1716 2445 [1509 1518 1520 1547 1311 2424 2408 2380 1791 $, 1602 1518 1520 1547 1311 2424 2408 2380 1791 $]]),

((ATNState 0x2974a50) {
  state: INVALID  (1413)
  ruleIndex: 115
  epsilonOnlyTransitions: 0
  transistions (1):
    SET (Transition 0x29adea0, target: 0x2974ab0) { set: {118..119}}
},
2,
[1716 2445 [1509 1518 1520 1547 1311 2424 2408 2380 1791 $, 1602 1518 1520 1547 1311 2424 2408 2380 1791 $]])

(1413,
2,
[1716 2445 [1509 1518 1520 1547 1311 2424 2408 **2366** 1791 $, 1602 1518 1520 1547 1311 2424 2408 **2366** 1791 $]]),
```

**Comment by mike-lischke** [comment] 2016-08-01 16:25
@Nic30 Please test with the new patches and let me know if those fix the problems you saw here. I merged everything into master so you can just pull the repo.

**Comment by Nic30** [comment] 2016-08-01 16:26
I am testing.

**Comment by Nic30** [comment] 2016-08-03 12:00
Issue appears if atn::ParserATNSimulator::mergeCache is in use.
It seems that there is some pointer in keys which is not working (If I try to dump them in ParserATNSimulator::closure_  before configs->add(config, &mergeCache); (where my configs becomes invalid...) program fails on segfault, but If I don't print mergeCache everything seems to be ok. )
Number of items in mergeCache seems to be valid all the times.

Is there any easy way how to disable mergeCache to check if it is causing the issue?

**Comment by mike-lischke** [comment] 2016-08-03 12:38
Hmm, we use raw pointer pairs for the key, as I thought they would be valid during the (short) lifetime of the cache content. You can, as a test, make them Refs too and see if that solves your issue.

**Comment by Nic30** [comment] 2016-08-03 12:50
I will try, but it seems that keys are wrong for example:
(merge is at start of PredictionContext::merge)

cpp:
CALL rule identifier, ctx=1595 1518 1520 1547 1311 2424 2408 2366 1791 $
closure((230,2,[1420 1595 1518 1520 1547 1311 2424 2408 2366 1791 $]))
closure((1413,2,[1420 1595 1518 1520 1547 1311 2424 2408 2366 1791 $]))
merge: size:2
   1311 2424 2408 2366 1791 $ 1518 1520 1547 1311 2424 2408 2380 1791 $
      [1502 1518 1520 1547 1311 2424 2408 2380 1791 $, 1595 1518 1520 1547 1311 2424 2408 2380 1791 $]
   2424 2408 2366 1791 $ 1518 1520 1547 1311 2424 2408 2380 1791 $
      1420 [1502 1518 1520 1547 1311 2424 2408 2380 1791 $, 1595 1518 1520 1547 1311 2424 2408 2380 1791 $]
closure_ configs after add mergeCache:[(1498,1,[1518 1520 1547 1311 2424 2408 2380 1791 $]), (1413,1,[1420 [1502 1518 1520 1547 1311 2424 2408 2380 1791 $, 1595 1518 1520 1547 1311 2424 2408 2380 1791 $]]), (1572,1,[1518 1520 1547 1311 2424 2408 2380 1791 $]), (1591,1,[1518 1520 1547 1311 2424 2408 2380 1791 $]), (1521,1,[1518 1520 1547 1311 2424 2408 2380 1791 $]), (1586,1,[1518 1520 1547 1311 2424 2408 2380 1791 $]), (1550,1,[1518 1520 1547 1311 2424 2408 2380 1791 $]), (1498,2,[1518 1520 1547 1311 2424 2408 2366 1791 $]), (1413,2,[1420 [1502 1518 1520 1547 1311 2424 2408 2366 1791 $, 1595 1518 1520 1547 1311 2424 2408 2366 1791 $]]), (1572,2,[1518 1520 1547 1311 2424 2408 2366 1791 $]), (1591,2,[1518 1520 1547 1311 2424 2408 2366 1791 $])]


java 
CALL rule identifier, ctx=1595 1518 1520 1547 1311 2424 2408 2366 1791 $
closure((230,2,[1420 1595 1518 1520 1547 1311 2424 2408 2366 1791 $]))
closure((1413,2,[1420 1595 1518 1520 1547 1311 2424 2408 2366 1791 $]))
merge: size:2
   1502 1518 1520 1547 1311 2424 2408 2380 1791 $
      [1502 1518 1520 1547 1311 2424 2408 2380 1791 $, 1595 1518 1520 1547 1311 2424 2408 2380 1791 $]
   1420 1502 1518 1520 1547 1311 2424 2408 2380 1791 $
      1420 [1502 1518 1520 1547 1311 2424 2408 2380 1791 $, 1595 1518 1520 1547 1311 2424 2408 2380 1791 $]
merge: size:2
   1502 1518 1520 1547 1311 2424 2408 2380 1791 $
      [1502 1518 1520 1547 1311 2424 2408 2380 1791 $, 1595 1518 1520 1547 1311 2424 2408 2380 1791 $]
   1420 1502 1518 1520 1547 1311 2424 2408 2380 1791 $
      1420 [1502 1518 1520 1547 1311 2424 2408 2380 1791 $, 1595 1518 1520 1547 1311 2424 2408 2380 1791 $]
closure_ configs after add mergeCache:[(1498,1,[1518 1520 1547 1311 2424 2408 2380 1791 $]), (1413,1,[1420 [1502 1518 1520 1547 1311 2424 2408 2380 1791 $, 1595 1518 1520 1547 1311 2424 2408 2380 1791 $]]), (1572,1,[1518 1520 1547 1311 2424 2408 2380 1791 $]), (1591,1,[1518 1520 1547 1311 2424 2408 2380 1791 $]), (1521,1,[1518 1520 1547 1311 2424 2408 2380 1791 $]), (1586,1,[1518 1520 1547 1311 2424 2408 2380 1791 $]), (1550,1,[1518 1520 1547 1311 2424 2408 2380 1791 $]), (1498,2,[1518 1520 1547 1311 2424 2408 2366 1791 $]), (1413,2,[1420 [1502 1518 1520 1547 1311 2424 2408 2366 1791 $, 1595 1518 1520 1547 1311 2424 2408 2366 1791 $]]), (1572,2,[1518 1520 1547 1311 2424 2408 2366 1791 $]), (1591,2,[1518 1520 1547 1311 2424 2408 2366 1791 $])]


(content of merge cache is different)

**Comment by Nic30** [comment] 2016-08-03 14:06
@mike-lischke replacing pointers with Ref<> did help, but it seems that is because cache is not working.
(it seems to me, I will try to prove it.)

**Comment by mike-lischke** [comment] 2016-08-04 08:07
It's not 100% clear to me what you are saying. Do you mean that changing the raw pointers to Ref<> solved your issue reported here? Or did it only help because you entirely disabled the cache (which would be bad)?

**Comment by Nic30** [comment] 2016-08-04 08:17
I changed the raw pointers to Ref<> in mergeCache,
I also made mergeCache just a pointer in it's parent class (and I add proper new/delete, like it is in java).
And I replace some weak pointers with Ref<> because they were loosing the thing which they were pointing at.

mergeCache is somehow working, but it seems that cpp parser will compute closure much more times (compare to java).
 I think that is because mergeCache is not working.

You can check my debugging code at:
https://github.com/Nic30/hdlConvertor/tree/master/src/antlr4-runtime-cpp/atn

But it would be maybe better to send pull request to this repo. What do you think?

**Comment by mike-lischke** [comment] 2016-08-04 14:07
Ok, I checked myself and indeed all VHDL examples now parse fine. I just have pushed my fix, so there is no need for you to create a pull request. Please test yourself and if everything is fine close this issue.

**Comment by nuuman** [comment] 2016-08-05 14:25
@mike-lischke my stuff works now as well. Thanks for fixing this!

**Comment by mike-lischke** [comment] 2016-08-05 14:55
@nuuman I'm glad to hear that. Btw, can you please sign the contributors list?

**Comment by nuuman** [comment] 2016-08-05 17:10
@mike-lischke I've contributed to many open source projects in the past and never had to sign anything. What does it mean and why do I have to do it?

**Comment by DanMcLaughlin** [comment] 2016-08-05 17:13
@nuuman "to keep the licensing clean" according to Terence, basically a requirement for Antr direct from the supreme dictator

**Comment by nuuman** [comment] 2016-08-05 17:15
wut

**Comment by mike-lischke** [comment] 2016-08-05 18:14
ANTLR is used by many, also big, companies and they have quite strict license requirements. Also, Terence has to ensure he cannot be held responsible for code contributions that might bring him legal trouble. It's just a small line to add and also an honour to be mentioned side-by-side with the famous devs. Think of reputation, rather than privacy issues ;-)

**Comment by nuuman** [comment] 2016-08-05 18:56
@mike-lischke I decided against changing this, because it doesn't hold water legally.

For starters, it's inconsistent with the license of the project:

> Neither the name of the author nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

since the agreement says

> [...] is maintained indefinitely and may be redistributed consistent with this project [...]

where "consistent with this project" is undefined.

Even worse:

> I agree to  defend, indemnify, and hold The ANTLR Project and ANTLR users harmless from any claim or demand, including reasonable attorney  fees, made by any third party due to or arising out of my violation  of these terms and conditions or my violation of the rights of  another person or entity.

Absolutely not.

I'm not trying to be difficult here, but this agreement is highly unusual and legally unsound.

**Comment by parrt** [comment] 2016-08-05 21:37
@nuuman I totally understand the odiousness of this. We will try to remove your contribution.  How much code are we talking about? 

Please note that Eclipse foundation lawyers used to praise this license cleanliness in the multiple calls I've had with them about including ANTLR etc... in eclipse.

**Comment by mike-lischke** [comment] 2016-08-06 07:56
It's essentially a bug fix we have to do anyway. I can remove nuuman's code, but I would have to add it back immediately since it fixes something that must be fixed :-) The code is in patch #9.

**Comment by Nic30** [comment] 2016-08-06 11:38
@mike-lischke I know about two another problems caused by lost references, I also found that recent "performance fixes" caused some of my tests to run 10^4(+) times longer. 
You can close this issue, because it was solved by fixing mergeCache.
As soon as I have time I will send you pull request with fix for another issues which I have found.

**Comment by mike-lischke** [comment] 2016-08-06 12:09
@Nic30 There have been no performance related additions/changes lately. All we we did in the past weeks was to solve problems with wrong parsing. If tests now run so much longer then it probably means things are not cached (e.g. the computed DFAs, configs or similar).

**Closed by mike-lischke** 2016-08-06 12:09 UTC

**Comment by nuuman** [comment] 2016-08-06 21:53
@parrt almost no code at all, but I had a lot lined up for a dot-file generator that worked with the c++ target (which I hoped would be accepted)

I'll keep that in a separate repo.
